/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoAnfrageRouteImport } from './routes/demo-anfrage'
import { Route as IndexRouteImport } from './routes/index'

const DemoAnfrageRoute = DemoAnfrageRouteImport.update({
  id: '/demo-anfrage',
  path: '/demo-anfrage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-anfrage': typeof DemoAnfrageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-anfrage': typeof DemoAnfrageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-anfrage': typeof DemoAnfrageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo-anfrage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo-anfrage'
  id: '__root__' | '/' | '/demo-anfrage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoAnfrageRoute: typeof DemoAnfrageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-anfrage': {
      id: '/demo-anfrage'
      path: '/demo-anfrage'
      fullPath: '/demo-anfrage'
      preLoaderRoute: typeof DemoAnfrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoAnfrageRoute: DemoAnfrageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
