/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DemoAnfrageRouteImport } from './routes/demo-anfrage'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAnfrageRoute = DemoAnfrageRouteImport.update({
  id: '/demo-anfrage',
  path: '/demo-anfrage',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/demo-anfrage': typeof DemoAnfrageRoute
  '/impressum': typeof ImpressumRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/demo-anfrage': typeof DemoAnfrageRoute
  '/impressum': typeof ImpressumRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/demo-anfrage': typeof DemoAnfrageRoute
  '/impressum': typeof ImpressumRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/datenschutz'
    | '/demo-anfrage'
    | '/impressum'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/datenschutz'
    | '/demo-anfrage'
    | '/impressum'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/datenschutz'
    | '/demo-anfrage'
    | '/impressum'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  DemoAnfrageRoute: typeof DemoAnfrageRoute
  ImpressumRoute: typeof ImpressumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-anfrage': {
      id: '/demo-anfrage'
      path: '/demo-anfrage'
      fullPath: '/demo-anfrage'
      preLoaderRoute: typeof DemoAnfrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  DemoAnfrageRoute: DemoAnfrageRoute,
  ImpressumRoute: ImpressumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
